In [1]:
import pandas as pd
df_cartel = pd.read_excel("/Users/alexandertrejo/Documents/Locus Analytica/Desaparecidos/Alex/desaparecidos/Alex Bd/Project/Cartel_anio_estado_presi.xlsx")
df_cartel.head()

    año           estado       cartel           presidente
0  1976          Sinaloa  guadalajara  José López Portillo
1  1976        Chihuahua  guadalajara  José López Portillo
2  1976  Baja California  guadalajara  José López Portillo
3  1976           Sonora  guadalajara  José López Portillo
4  1976          Jalisco  guadalajara  José López Portillo

In [2]:
df_gobernadores = pd.read_excel("/Users/alexandertrejo/Documents/Locus Analytica/Desaparecidos/Alex/desaparecidos/Alex Bd/Project/GObernadoresCronologicamente.xlsx")
df_gobernadores[['Año Inicial', 'Año Final']] = df_gobernadores['Periodo'].str.split('-', expand=True)
df_gobernadores['Estado'] = df_gobernadores['Estado'].str.lower().str.capitalize()
df_gobernadores

,Estado,Gobernador,Partido,Periodo,Año Inicial,Año Final
0,Aguascalientes,Felipe González González,Partido Acción Nacional,2000-2004,2000,2004
1,Aguascalientes,Luis Armando Reynoso Femat,Partido Acción Nacional,2004-2010,2004,2010
2,Aguascalientes,Carlos Lozano de la Torre,Partido Revolucionario Institucional,2010-2016,2010,2016
3,Aguascalientes,Martín Orozco Sandoval,Partido Acción Nacional,2016-2022,2016,2022
4,Baja california,Eugenio Elorduy Walther,Partido Acción Nacional,2001-2007,2001,2007
...,...,...,...,...,...,...
140,Yucatán,Mauricio Vila Dosal,Partido Acción Nacional,2018-presente,2018,presente
141,Zacatecas,Ricardo Monreal Ávila,PT/PRD,1998-2004,1998,2004
142,Zacatecas,Amalia García Medina,Partido de la Revolucion Democratica,2004-2010,2004,2010
143,Zacatecas,Miguel Alonso Reyes,Partido Revolucionario Institucional,2010-2016,2010,2016
144,Zacatecas,Alejandro Tello Cristerna,Partido Revolucionario Institucional,2016-presente,2016,presente

In [3]:
lista1 = df_gobernadores['Estado'].unique().tolist()

In [4]:
lista2 = df_cartel['estado'].unique().tolist()

In [5]:
if any(elemento in lista2 for elemento in lista1):
    print("Las listas tienen elementos comunes.")
else:
    print("Las listas no tienen elementos comunes.")

elementos_faltantes = set(lista1) - set(lista2)

print("Elementos de lista1 que no están en lista2:")
print(elementos_faltantes)

Las listas tienen elementos comunes.
Elementos de lista1 que no están en lista2:
{'Ciudad de méxico', 'Baja california sur', 'Quintana roo', 'Nuevo león', 'San luis potosí', 'Baja california', 'Estado de méxico'}

In [6]:
df_gobernadores['Estado'] = df_gobernadores['Estado'].replace('San luis potosí', 'San Luis Potosí')
df_gobernadores['Estado'] = df_gobernadores['Estado'].replace('Estado de méxico', 'Estado de México')
df_gobernadores['Estado'] = df_gobernadores['Estado'].replace('Ciudad de méxico', 'Ciudad de México')
df_cartel['estado'] = df_cartel['estado'].replace('Distrito Federal', 'Ciudad de México')
df_gobernadores['Estado'] = df_gobernadores['Estado'].replace('Baja california sur', 'Baja California Sur')
df_gobernadores['Estado'] = df_gobernadores['Estado'].replace('Baja california', 'Baja California')
df_gobernadores['Estado'] = df_gobernadores['Estado'].replace('Quintana roo', 'Quintana Roo')
df_gobernadores['Estado'] = df_gobernadores['Estado'].replace('Nuevo león', 'Nuevo León')

In [7]:
lista1 = df_gobernadores['Estado'].unique().tolist()
lista2 = df_cartel['estado'].unique().tolist()

if any(elemento in lista2 for elemento in lista1):
    print("Las listas tienen elementos comunes.")
else:
    print("Las listas no tienen elementos comunes.")

elementos_faltantes = set(lista1) - set(lista2)

print("Elementos de lista1 que no están en lista2:")
print(elementos_faltantes)

Las listas tienen elementos comunes.
Elementos de lista1 que no están en lista2:
set()

In [8]:
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2001', '2000')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2002', '2000')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2003', '2000')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2004', '2000')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2005', '2000')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2007', '2006')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2008', '2006')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2009', '2006')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2010', '2006')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2011', '2006')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2013', '2012')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2014', '2012')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2015', '2012')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2016', '2012')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2017', '2012')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2019', '2018')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2020', '2018')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2021', '2018')
df_gobernadores['Año Inicial'] = df_gobernadores['Año Inicial'].replace('2022', '2018')
años_mayores_2000 = df_gobernadores['Año Inicial'][df_gobernadores['Año Inicial'].astype(int) > 2000].unique().tolist()

In [9]:
df_cartel_1 = df_cartel.groupby(['año', 'estado','presidente'])['cartel'].apply(','.join).reset_index()
df_cartel_1

,año,estado,presidente,cartel
0,1976,Baja California,José López Portillo,guadalajara
1,1976,Chihuahua,José López Portillo,guadalajara
2,1976,Durango,José López Portillo,guadalajara
3,1976,Jalisco,José López Portillo,guadalajara
4,1976,Michoacán,José López Portillo,milenio
...,...,...,...,...
160,2018,Sinaloa,AMLO,sinaloa
161,2018,Sonora,AMLO,"sinaloa,juarez,tijuana,beltran-leyva"
162,2018,Tabasco,AMLO,"golfo,zetas"
163,2018,Tamaulipas,AMLO,"golfo,zetas"
164,2018,Veracruz,AMLO,"golfo,zetas,jalisco-nueva-generacion"

In [10]:
df_gobernadores['cve_Estado_anio']=df_gobernadores['Estado']+"_"+df_gobernadores['Año Inicial'].astype(str)
df_cartel_1['cve_Estado_anio']=df_cartel_1["estado"]+"_"+df_cartel_1['año'].astype(str)

In [11]:
tablaconjunta=pd.merge(df_gobernadores,df_cartel_1,on="cve_Estado_anio",how="inner")
tablaconjunta

,Estado,Gobernador,Partido,Periodo,Año Inicial,Año Final,cve_Estado_anio,año,estado,presidente,cartel
0,Aguascalientes,Felipe González González,Partido Acción Nacional,2000-2004,2000,2004,Aguascalientes_2000,2000,Aguascalientes,Vicente Fox,colima
1,Aguascalientes,Luis Armando Reynoso Femat,Partido Acción Nacional,2004-2010,2000,2010,Aguascalientes_2000,2000,Aguascalientes,Vicente Fox,colima
2,Aguascalientes,Martín Orozco Sandoval,Partido Acción Nacional,2016-2022,2012,2022,Aguascalientes_2012,2012,Aguascalientes,Enrique Peña Nieto,beltran-leyva
3,Baja California,Eugenio Elorduy Walther,Partido Acción Nacional,2001-2007,2000,2007,Baja California_2000,2000,Baja California,Vicente Fox,"sinaloa,tijuana,colima"
4,Baja California,José Guadalupe Osuna Millán,Partido Acción Nacional,2007-2013,2006,2013,Baja California_2006,2006,Baja California,Felipe Calderón,"sinaloa,tijuana"
...,...,...,...,...,...,...,...,...,...,...,...
100,Veracruz,Miguel Ángel Yunes Linares,Partido Acción Nacional,2016-2018,2012,2018,Veracruz_2012,2012,Veracruz,Enrique Peña Nieto,"golfo,zetas,jalisco-nueva-generacion"
101,Veracruz,Cuitláhuac García Jiménez,Morena,2018-presente,2018,presente,Veracruz_2018,2018,Veracruz,AMLO,"golfo,zetas,jalisco-nueva-generacion"
102,Yucatán,Patricio Patrón Laviada,Partido Acción Nacional,2001-2007,2000,2007,Yucatán_2000,2000,Yucatán,Vicente Fox,"sinaloa,golfo"
103,Zacatecas,Amalia García Medina,Partido de la Revolucion Democratica,2004-2010,2000,2010,Zacatecas_2000,2000,Zacatecas,Vicente Fox,"juarez,tijuana"
104,Zacatecas,Miguel Alonso Reyes,Partido Revolucionario Institucional,2010-2016,2006,2016,Zacatecas_2006,2006,Zacatecas,Felipe Calderón,"juarez,zetas"

In [12]:
df_desaparecidos = pd.read_csv("/Users/alexandertrejo/Documents/Locus Analytica/Desaparecidos/Alex/desaparecidos/Alex Bd/Project/BD_Hasta2023_TODOElPAIS.csv")
df_desaparecidos.head()

,fecha,estado,hombres_edo,mujeres_edo,indeterminado_edo,municipio,hombres_mun,mujeres_mun,indeterminado_mun,hombres_circunstancia_1,...,indeterminado_estatus_personas_desaparecidas,hombres_estatus_personas_no_localizadas,mujeres_estatus_personas_no_localizadas,indeterminado_estatus_personas_no_localizadas,hombres_estatus_personas_localizadas,mujeres_estatus_personas_localizadas,indeterminado_estatus_personas_localizadas,hombres_estatus_personas_desaparecidas_y_no_localizadas,mujeres_estatus_personas_desaparecidas_y_no_localizadas,indeterminado_estatus_personas_desaparecidas_y_no_localizadas
0,2000-01-01,GUERRERO,7.0,0.0,0.0,ACAPULCO DE JUÁREZ,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
1,2000-01-01,GUERRERO,NaN,NaN,NaN,COCULA,1.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-01-01,GUERRERO,NaN,NaN,NaN,IGUALA DE LA INDEPENDENCIA,5.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-01-01,JALISCO,1.0,0.0,0.0,SE DESCONOCE,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,2000-01-01,NUEVO LEON,1.0,0.0,0.0,MONTERREY,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [13]:
df_desaparecidos['fecha']= pd.to_datetime(df_desaparecidos['fecha']).dt.year
df_desaparecidos['fecha']

0        2000
1        2000
2        2000
3        2000
4        2000
         ...
98445    2022
98446    2022
98447    2022
98448    2022
98449    2022
Name: fecha, Length: 98450, dtype: int64

In [14]:
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2001, 2000)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2002, 2000)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2003, 2000)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2004, 2000)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2005, 2000)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2007, 2006)
df_desaparecidos['fecha']= df_desaparecidos['fecha'].replace(2008, 2006)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2009, 2006)
df_desaparecidos['fecha']= df_desaparecidos['fecha'].replace(2010, 2006)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2011, 2006)
df_desaparecidos['fecha']= df_desaparecidos['fecha'].replace(2013, 2012)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2014, 2012)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2015, 2012)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2016, 2012)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2017, 2012)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2019, 2018)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2020, 2018)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2021, 2018)
df_desaparecidos['fecha'] = df_desaparecidos['fecha'].replace(2022, 2018)

In [15]:
df_desaparecidos['estado'] = df_desaparecidos['estado'].str.lower().str.capitalize()
df_desaparecidos.head()

,fecha,estado,hombres_edo,mujeres_edo,indeterminado_edo,municipio,hombres_mun,mujeres_mun,indeterminado_mun,hombres_circunstancia_1,...,indeterminado_estatus_personas_desaparecidas,hombres_estatus_personas_no_localizadas,mujeres_estatus_personas_no_localizadas,indeterminado_estatus_personas_no_localizadas,hombres_estatus_personas_localizadas,mujeres_estatus_personas_localizadas,indeterminado_estatus_personas_localizadas,hombres_estatus_personas_desaparecidas_y_no_localizadas,mujeres_estatus_personas_desaparecidas_y_no_localizadas,indeterminado_estatus_personas_desaparecidas_y_no_localizadas
0,2000,Guerrero,7.0,0.0,0.0,ACAPULCO DE JUÁREZ,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0
1,2000,Guerrero,NaN,NaN,NaN,COCULA,1.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000,Guerrero,NaN,NaN,NaN,IGUALA DE LA INDEPENDENCIA,5.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,Jalisco,1.0,0.0,0.0,SE DESCONOCE,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,2000,Nuevo leon,1.0,0.0,0.0,MONTERREY,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [16]:
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Yucatan', 'Yucatán')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Quintana roo', 'Quintana Roo')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Estado de mexico', 'Estado de México')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Queretaro', 'Querétaro')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Baja california', 'Baja California')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('San luis potosi','San Luis Potosí')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Michoacan','Michoacán')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Ciudad de mexico','Ciudad de México')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Baja california sur', 'Baja California Sur')
df_desaparecidos['estado'] = df_desaparecidos['estado'].replace('Nuevo leon','Nuevo León')
lista1 = df_desaparecidos['estado'].unique().tolist()
lista2 = tablaconjunta['estado'].unique().tolist()

if any(elemento in lista2 for elemento in lista1):
    print("Las listas tienen elementos comunes.")
else:
    print("Las listas no tienen elementos comunes.")

elementos_faltantes = set(lista1) - set(lista2)

print("Elementos de lista1 que no están en lista2:")
print(elementos_faltantes)

Las listas tienen elementos comunes.
Elementos de lista1 que no están en lista2:
{'Se desconoce'}

In [29]:
# En el archivo hay 335 personas sin estado
df_desaparecidos[df_desaparecidos['estado']=='Se desconoce'].shape[0]

335

In [17]:
df_desaparecidos['cve_Estado_anio']=df_desaparecidos["estado"]+"_"+df_desaparecidos['fecha'].astype(str)

0                Guerrero_2000
1                Guerrero_2000
2                Guerrero_2000
3                 Jalisco_2000
4              Nuevo León_2000
                 ...
98445             Durango_2018
98446          Nuevo León_2018
98447    Ciudad de México_2018
98448          Nuevo León_2018
98449          Tamaulipas_2018
Name: cve_Estado_anio, Length: 98450, dtype: object

In [18]:
tablaconjuntadesap=pd.merge(df_desaparecidos,tablaconjunta,on="cve_Estado_anio",how="inner")

In [20]:
tablaconjuntadesap=tablaconjuntadesap[['cve_Estado_anio','año','Estado','municipio','hombres_edo','mujeres_edo','indeterminado_edo','cartel','Gobernador',"Partido","presidente"]]
tablaconjuntadesap

,cve_Estado_anio,año,Estado,municipio,hombres_edo,mujeres_edo,indeterminado_edo,cartel,Gobernador,Partido,presidente
0,Guerrero_2000,2000,Guerrero,ACAPULCO DE JUÁREZ,7.0,0.0,0.0,"golfo,beltran-leyva,zetas",René Juárez Cisneros,Partido Revolucionario Institucional,Vicente Fox
1,Guerrero_2000,2000,Guerrero,COCULA,NaN,NaN,NaN,"golfo,beltran-leyva,zetas",René Juárez Cisneros,Partido Revolucionario Institucional,Vicente Fox
2,Guerrero_2000,2000,Guerrero,IGUALA DE LA INDEPENDENCIA,NaN,NaN,NaN,"golfo,beltran-leyva,zetas",René Juárez Cisneros,Partido Revolucionario Institucional,Vicente Fox
3,Guerrero_2000,2000,Guerrero,TIXTLA DE GUERRERO,1.0,0.0,0.0,"golfo,beltran-leyva,zetas",René Juárez Cisneros,Partido Revolucionario Institucional,Vicente Fox
4,Guerrero_2000,2000,Guerrero,IGUALA DE LA INDEPENDENCIA,1.0,0.0,0.0,"golfo,beltran-leyva,zetas",René Juárez Cisneros,Partido Revolucionario Institucional,Vicente Fox
...,...,...,...,...,...,...,...,...,...,...,...
76198,Durango_2018,2018,Durango,DURANGO,1.0,1.0,0.0,"sinaloa,juarez",José Rosas Aispuro Torres,Partido Acción Nacional,AMLO
76199,Durango_2018,2018,Durango,NaN,NaN,NaN,NaN,"sinaloa,juarez",José Rosas Aispuro Torres,Partido Acción Nacional,AMLO
76200,Durango_2018,2018,Durango,DURANGO,1.0,0.0,0.0,"sinaloa,juarez",José Rosas Aispuro Torres,Partido Acción Nacional,AMLO
76201,Durango_2018,2018,Durango,NaN,NaN,NaN,NaN,"sinaloa,juarez",José Rosas Aispuro Torres,Partido Acción Nacional,AMLO
76202,Durango_2018,2018,Durango,DURANGO,0.0,1.0,0.0,"sinaloa,juarez",José Rosas Aispuro Torres,Partido Acción Nacional,AMLO

In [21]:
#df_agrupado = tablaconjuntadesap.groupby(['Estado','año']).agg({'hombres_edo': 'sum', 'mujeres_edo': 'sum','indeterminado_edo': 'sum'}).reset_index()
#df_agrupado['cve_Estado_anio']=df_agrupado["Estado"]+"_"+df_agrupado['año'].astype(str)
#df_agrupadodesap=pd.merge(df_agrupado,tablaconjuntadesap,on="cve_Estado_anio",how="inner")
#df_agrupadodesap=df_agrupadodesap[["año_x","Estado_x","hombres_edo_x","mujeres_edo_x",'indeterminado_edo_x',"Gobernador","Partido","cartel","presidente"]]
#df_agrupadodesap = df_agrupadodesap.drop_duplicates(subset=['año_x', 'Estado_x'])
#df_agrupadodesap

,Estado,año,hombres_edo,mujeres_edo,indeterminado_edo,cve_Estado_anio
0,Aguascalientes,2000,0.0,0.0,0.0,Aguascalientes_2000
1,Aguascalientes,2012,81.0,49.0,0.0,Aguascalientes_2012
2,Baja California,2000,4.0,3.0,0.0,Baja California_2000
3,Baja California,2006,81.0,17.0,0.0,Baja California_2006
4,Baja California,2012,486.0,346.0,0.0,Baja California_2012
...,...,...,...,...,...,...
84,Veracruz,2012,1609.0,344.0,1.0,Veracruz_2012
85,Veracruz,2018,793.0,316.0,0.0,Veracruz_2018
86,Yucatán,2000,11.0,6.0,0.0,Yucatán_2000
87,Zacatecas,2000,5.0,2.0,0.0,Zacatecas_2000
88,Zacatecas,2006,278.0,33.0,0.0,Zacatecas_2006